version: '3.9'

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: medusa_admin
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: medusa_store
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local

